name: Action Test

on:
  push:
    branches: 
      - testsMocha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        npm test
